// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for landingPageImage documents
 */
interface LandingpageimageDocumentData {
  /**
   * image field in *landingPageImage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpageimage.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *landingPageImage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: title of image
   * - **API ID Path**: landingpageimage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * landingPageImage document from Prismic
 *
 * - **API ID**: `landingpageimage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingpageimageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingpageimageDocumentData>,
    "landingpageimage",
    Lang
  >;

/**
 * Content for WorkItem documents
 */
interface WorkitemDocumentData {
  /**
   * name field in *WorkItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name of work item
   * - **API ID Path**: workitem.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * workItemTitle field in *WorkItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g "Eddan Icelandic film awards"
   * - **API ID Path**: workitem.workitemtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  workitemtitle: prismic.KeyTextField;

  /**
   * workitemstatus field in *WorkItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g "Nomination"
   * - **API ID Path**: workitem.workitemstatus
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  workitemstatus: prismic.KeyTextField;

  /**
   * workitemartist field in *WorkItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g "Magnús Jóhann"
   * - **API ID Path**: workitem.workitemartist
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  workitemartist: prismic.KeyTextField;

  /**
   * workitemyear field in *WorkItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g "2025"
   * - **API ID Path**: workitem.workitemyear
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  workitemyear: prismic.KeyTextField;

  /**
   * workitemdescription field in *WorkItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: description of work
   * - **API ID Path**: workitem.workitemdescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  workitemdescription: prismic.KeyTextField;

  /**
   * workitemimage field in *WorkItem*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: workitem.workitemimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  workitemimage: prismic.ImageField<never>;
}

/**
 * WorkItem document from Prismic
 *
 * - **API ID**: `workitem`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkitemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<WorkitemDocumentData>,
    "workitem",
    Lang
  >;

export type AllDocumentTypes = LandingpageimageDocument | WorkitemDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LandingpageimageDocument,
      LandingpageimageDocumentData,
      WorkitemDocument,
      WorkitemDocumentData,
      AllDocumentTypes,
    };
  }
}
